[project]
name = "star-resonance-relay"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "discord-py>=2.6.4",
    "protobuf>=6.33.6",
    "requests>=2.32.5",
    "scapy>=2.7.0",
    "zstandard>=0.25.0",
    "polars>=1.40.1",
]

[project.scripts]
star-resonance-relay = "star_resonance_relay.bot:main"

[dependency-groups]
dev = [
    "grpcio-tools>=1.80.0",
    "ipykernel>=7.2.0"
]
build = [
    "grpcio-tools>=1.80.0",
]

[build-system]
requires = ["uv_build>=0.10.4,<0.11.0"]
build-backend = "uv_build"
